
[tasks.start]
depends = "start:*"
[tasks."start:frontend"]
run = "npm run dev"

[tasks."start:backend"]
run = "php artisan serve"

[tasks.test]
run = "composer exec --verbose phpunit"

[tasks.lint]
run = [
    "mise run lint:php",
    "mise run lint:js"
]

[tasks."lint:php"]
quiet = true
run = "composer exec --verbose pint"

[tasks."lint:js"]
quiet = true
run = "npm run lint"

[tasks.setup]
run = [
    "mise run install",
    "mise run prepare"
]
[tasks.install]
depends = "install:*"

[tasks."install:php"]
run = "composer install --no-progress"

[tasks."install:js"]
run = "npm ci"

[tasks."prepare:assets"]
wait_for = "install:js"
run = "npm run build"

[tasks."prepare:env"]
run = "cp .env.example .env --update=none"

[tasks."prepare:key"]
wait_for = ["prepare:env", "install"]
run = "php artisan key:generate"

[tasks.prepare]
run = [
    "mise run prepare:env",
    "mise run prepare:key",
    "mise run db:prepare",
    "mise run prepare:assets",
]

[tasks."db:prepare"]
run = [
    "mise run db:create",
    "mise run db:migrate",
    "mise run db:seed"
]

[tasks."db:create"]
run = [
    "touch database/database.sqlite"
]

[tasks."db:seed"]
run = "php artisan db:seed"

[tasks."db:migrate"]
run = "php artisan migrate"

[tasks."clean"]
run = [
    "rm -rf vendor",
    "rm -rf node_modules",
    "rm -rf build",
    "rm -rf .env",
    "rm -rf database/database.sqlite",
]

[tasks."clean-setup"]
run = [
    "mise run clean",
    "mise run setup",
]
