
[tasks.start]
depends = "start:*"
[tasks."start:frontend"]
run = "npm run dev"

[tasks."start:backend"]
run = "php artisan serve"

[tasks.test]
run = "composer exec --verbose phpunit"

[tasks.lint]
run = [
    "mise run lint:php",
    "mise run lint:js"
]

[tasks."lint:php"]
quiet = true
run = "composer exec --verbose pint"

[tasks."lint:js"]
quiet = true
run = "npm run lint"

[tasks.setup]
run = [
    "mise run install",
    "mise run prepare"
]
[tasks.install]
depends = "install:*"

[tasks."install:backend"]
run = "composer install --no-progress"

[tasks."install:frontend"]
run = "npm ci"

[tasks."prepare:assets"]
wait_for = "install:frontend"
run = "npm run build"

[tasks."prepare:env"]
run = "cp .env.example .env --update=none"

[tasks."prepare:key"]
wait_for = ["prepare:env", "install"]
run = "php artisan key:generate"

[tasks.prepare]
run = [
    "mise run prepare:env",
    "mise run prepare:key",
    "mise run prepare:assets"
]

[tasks."db:seed"]
run = "php artisan db:seed"

[tasks."db:migrate"]
run = "php artisan db:migrate"

[tasks."clean"]
run = [
    "rm -rf vendor",
    "rm -rf node_modules",
    "rm -rf build",
    "rm -rf .env",
]

[tasks."clean-setup"]
depends = ["clean"]
run = [
    "mise run setup"
]
